services:
  db:
    image: mysql:latest
    environment:
      - DB_HOST=db
      - DB_PORT=${MYSQL_PORT}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - app_network

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/go/src/
    ports:
      - "8080:8080"
    depends_on:
      - db
    tty: true
    stdin_open: true
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true

  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/openapi/src/openapi.yaml
    volumes:
      - ./openapi/src/openapi.yaml:/openapi/openapi.yaml
    ports:
      - "8011:8080"

  prism:
    image: stoplight/prism:4
    command: 'mock -h 0.0.0.0 /openapi/openapi.yaml'
    volumes:
      - ./openapi/src/openapi.yaml:/openapi/openapi.yaml:ro
    ports:
      - "4010:4010"

volumes:
  mysql_data:

networks:
  app_network:
