name: Go Unit Test
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.23.x"]

    steps:
      - uses: actions/checkout@v5
      - name: Setup Go 1.23.x
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test -v ./...
